name: xyz

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/xyz.yml'
  
jobs:
  xyz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: fawazahmed0/action-debug-vscode@main
